algoritmo "primeiro exercicio"
var
inicio
tipo regPassagem = registro
     inteiro Numero
     cadeia Origem, Destino, Data, horario
     inteiro Poltrona
     real Distancia
fimregistro
regPassagem Passagem

Passagem.Numero = 1
Passagem.Origem = "Brasil"
Passagem.Destino = "Paraguai"
Passagem.data = "01/01/2023"
Passagem.horario = "19h00"
Passagem.Poltrona = 20
Passagem.Distancia = 100.20
fimalgoritmo